config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "countries#index"
  resources :countries, :places
  get "countries", to: "countries#index"
  get "countries/:id", to: "countries#show"
  get "countries/new", to: "countries#new"
  post "countries", to: "countries#create"

  get "countries/:id/edit", to: "countries#edit", as: :country_edit
  patch "countries/:id", to: "countries#update"
  delete "countries/:id", to: "countries#destroy"

  get "places/new", to: "places#new"
  post "places", to: "places#create"

  ###############
  post "places/:id", to: "places#show"
  ################
  get "places/:id/edit", to: "places#edit", as: :place_edit

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    belongs_to :user
    has_many :places, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :country
end

app/models/user.rb
class User < ApplicationRecord
  has_many :countries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @countries = Country.all
        # @countries = Country.where(user_id: current_user.id)
        # @places = @countries.places
    end

    def show
        @country = Country.find(params[:id])
        @places = @country.places
    end

    def new
        @country = Country.new
    end

    def create
        # Country.create(params.require(:country).permit(:name, :img, :info, :bestplase))
        # redirect_to countries_path
        @country = Country.new(params.require(:country).permit(:name, :img, :info)) 
        @country.user_id = current_user.id
        @country.save
        redirect_to countries_path
    end

    def edit
        @country = Country.find(params[:id])
    end

    def update
        country = Country.find(params[:id])
        country.update(params.require(:country).permit(:name, :img, :info))        
        redirect_to countries_path
    end

    def destroy
        Country.find(params[:id]).destroy
        redirect_to countries_path
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!
    def new
        @country = Country.find(params[:country_id])
        @place = Place.new
    end

    def create
        puts params
        country = Country.find(params[:place][:country_id])
        Place.create(params.require(:place).permit(:city, :info, :pic, :vid, :country_id))    
        redirect_to country
    end

    def show
        @place = Place.find(params[:id])
    end
    # error
    # def edit
        # @place = Place.find(params[:id])
    # end

    def destroy
        Place.find(params[:id]).destroy
        redirect_to places_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>

    <div class="input-field col s6 form-group">
        <%= f.label :name, 'Country Name' %>
        <%= f.text_field :name , class: "form-control" %>
    </div>

    <div class="input-field col s6 form-group">
        <%= f.label :img, 'Flag Image(URL)' %>
        <%= f.text_field :img , class: "form-control" %>
    </div>

    <div class="input-field col s6 form-group">
        <%= f.label :info, 'Information(About Country)' %>
        <%= f.text_field :info , class: "form-control" %>
    </div><br>

    <%= f.submit "Submit", :class => "btn btn-dark align-B" %>
  <% end %>

app/views/countries/edit.html.erb
<h1>Edit <%= @country.name %></h1>

<%= render 'countries/form' %>

app/views/countries/index.html.erb
<h1 class="display-3 text-center text-monospace" id="h1index">All Countries</h1>

<div class="indBtn"><%= link_to "Add Country", new_country_path, { :class => "btn btn-dark " } %></div>

<% if (current_user.id != 1) %>

  <div class="container">
<div class="row">
<div class="card-deck">
<% @countries.each do |country| %>
  <div class="col-sm-12 ">
  <div class="card cad">
  <div class="img"><%= image_tag(country.img, size: "150x80", alt: "Country Image") %></div>
    <div class="card-body">
      <h5 class="card-title fontIndxCou"><%= link_to country.name, country_path(country) %></h5>
      <p class="card-text fontIndxInfo"><%= country.info %></p>
      <p class="card-text fontIndxBest"><%= country.bestplase %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">
      <a class="glyphicon glyphicon-edit"></a>
      <a class="glyphicon glyphicon-remove"></a> 
      <a class="glyphicon glyphicon-plus"></a>
      </small>
    </div>
  </div>
  <br><br><br>
  </div>
  <% end %>
</div>
</div>
</div>

<% else %>

  <div class="container">
<div class="row">
<div class="card-deck">
<% @countries.each do |country| %>
  <div class="col-sm-12 ">
  <div class="card cad">
  <div class="img"><%= image_tag(country.img, size: "150x80", alt: "Country Image") %></div>
    <div class="card-body">
      <h5 class="card-title fontIndxCou"><%= link_to country.name, country_path(country) %></h5>
      <p class="card-text fontIndxInfo"><%= country.info %></p>
      <p class="card-text fontIndxBest"><%= country.bestplase %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">
      <a class="glyphicon glyphicon-edit" href="<%= edit_country_path(country) %>"></a>
      <a class="glyphicon glyphicon-remove" data-confirm="Are you sure you want to delete <%= country.name %>?" data-method="delete" href="/countries/<%= country.id %>" rel="nofollow"></a> 
      <a class="glyphicon glyphicon-plus"></a>
      </small>
    </div>
  </div>
  <br><br><br>
  </div>
  <% end %>
</div>
</div>
</div>

<% end %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'countries/form' %>

app/views/countries/show.html.erb
<h1 class="display-3 text-center text-monospace" id="h1Show"><%= @country.name %></h1>

<div class="indBtn"><%= link_to "New Place", new_place_path(:country_id => @country.id), { :class => "btn btn-dark" } %></div>

<div class="container">
<div class="row">
<div class="card-deck">
<% @places.each do |place| %>
  <div class="col-sm-12 ">
  <div class="card cad">
  <div class="img"><%= image_tag(place.pic, size: "150x80", alt: "Place Image") %></div>
    <div class="card-body">
      <h5 class="card-title fontIndxCou"><%= link_to place.city , place_path(place) %></h5>
      <p class="card-text fontIndxInfo"><%= place.info %></p>
      <p class="card-text fontIndxBest"><%= place.vid %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">
      <a class="glyphicon glyphicon-edit"></a>
      <a class="glyphicon glyphicon-remove"></a> 
      <a class="glyphicon glyphicon-plus"></a>
      </small>
    </div>
  </div>
  <br><br><br>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/layouts/_nav.html.erb
<p class="navbar navbar-light" style="background-color: #555555; color: #ffffff">
<% if user_signed_in? %>
  Logged in as : <%= current_user.email %>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldBestPlace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>

    <div class="text-monospace" id="form">
    <%= f.hidden_field :country_id, :value => @country.id %>
    </div>
    <div class="input-field col s6 form-group">
        <%= f.label :city, 'City Name' %>
        <%= f.text_field :city , class: "form-control"%>
    </div>
    <div class="input-field col s6 form-group">
        <%= f.label :info, 'Information(Location Name)' %>
        <%= f.text_field :info , class: "form-control"%>
    </div>
        <div class="input-field col s6 form-group">
        <%= f.label :pic, 'Image' %>
        <%= f.text_field :pic , class: "form-control"%>
    </div>
        <div class="input-field col s6 form-group">
        <%= f.label :vid, 'Video' %>
        <%= f.text_field :vid , class: "form-control"%>
    </div>
    <%= f.submit "Submit", :class => "btn btn-dark align-B" %>
  <% end %>

app/views/places/edit.html.erb
<%= render 'places/form' %>

app/views/places/new.html.erb
<h1>New Place for <%= @country.name %></h1>

<%= render 'places/form' %>

app/views/places/show.html.erb
<div class="card mb-3">
  <%= image_tag(@place.pic, class: "card-img-top", alt: "country Image") %>
  <div class="card-body">
    <h2 class="card-title"><%= @place.info %></h2>
    <p class="card-text"><a href="<%= @place.vid %>" target="_blank"><button class="btn btn-info">Video</button></a></p>
  </div>
</div